// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Api.ShoppingCart.Persistence;

namespace Store.Api.ShoppingCart.Migrations
{
    [DbContext(typeof(ShoppingCartContext))]
    partial class ShoppingCartContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Store.Api.ShoppingCart.Model.ShoppingCartSession", b =>
                {
                    b.Property<int>("ShoppingCartSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ShoppingCartSessionId");

                    b.ToTable("ShoppingCartSession");
                });

            modelBuilder.Entity("Store.Api.ShoppingCart.Model.ShoppingCartSessionDetail", b =>
                {
                    b.Property<int>("ShoppingCartSessionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SelectedProduct")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ShoppingCartSessionId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartSessionDetailId");

                    b.HasIndex("ShoppingCartSessionId");

                    b.ToTable("ShoppingCartSessionDetail");
                });

            modelBuilder.Entity("Store.Api.ShoppingCart.Model.ShoppingCartSessionDetail", b =>
                {
                    b.HasOne("Store.Api.ShoppingCart.Model.ShoppingCartSession", "CartSession")
                        .WithMany("DetailList")
                        .HasForeignKey("ShoppingCartSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
